import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApprovalRequest, ApprovalService } from '../../core/services/approval.service';
import { AuthService } from '../../core/services/auth.service';
import { StaffCategory, Store } from '../../core/models/domain.model';
import { ApiService } from '../../core/services/api.service';

@Component({ selector: 'app-approvals', standalone: true, imports: [CommonModule, FormsModule], template: `<section class="page"><span class="eyebrow">APPROVALS</span><h2>{{ isManager() ? 'Approval Requests' : 'My Approval Requests' }}</h2><p class="muted">{{ isManager() ? 'Pending requests for your assigned stores.' : 'Requests submitted for manager review.' }}</p><form *ngIf="isEmployee()" class="request-form" (submit)="$event.preventDefault(); submit()"><input name="entityType" [(ngModel)]="entityType" placeholder="Entity type" /><input name="entityId" [(ngModel)]="entityId" placeholder="Existing entity ID" /><input name="approvalType" [(ngModel)]="approvalType" placeholder="Approval type" /><select name="storeId" [(ngModel)]="storeId"><option *ngFor="let store of stores()" [value]="store.id">{{ store.name }}</option></select><button type="submit" [disabled]="submitting()">Submit request</button></form><p *ngIf="loading()">Loading requests...</p><p *ngIf="error()" class="error">{{ error() }}</p><p *ngIf="!loading() && !error() && requests().length === 0">No approval requests.</p><div class="list"><article *ngFor="let request of requests()"><div><strong>{{ request.entityType }} · {{ request.approvalType }}</strong><span>{{ request.storeName }} · requested by {{ request.requestedBy }}</span><small>{{ request.status }} · {{ request.createdAt | date:'short' }}</small><em *ngIf="request.rejectionReason">{{ request.rejectionReason }}</em></div><div class="actions" *ngIf="isManager() && request.status === 'Pending'"><button type="button" (click)="decide(request, true)">Approve</button><button type="button" class="reject" (click)="decide(request, false)">Reject</button></div></article></div></section>`, styles: [`.page{max-width:900px}.eyebrow{color:#899a94;font-size:10px;font-weight:700;letter-spacing:1.5px}.muted,small{color:#82908b;font-size:12px}.request-form{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:18px 0}.request-form input,.request-form select{border:1px solid #e5ebe6;border-radius:6px;padding:9px;font-size:12px}.request-form button{border:0;border-radius:6px;background:#d8f16e;color:#172523;cursor:pointer}.list{display:grid;gap:10px;margin-top:20px}article{display:flex;justify-content:space-between;gap:18px;background:#fff;border:1px solid #e5ebe6;border-radius:8px;padding:16px}article div:first-child{display:grid;gap:5px}span{color:#586963;font-size:12px}em{color:#a64d3b;font-size:11px}.actions{display:flex;gap:8px;align-items:center}.actions button{border:1px solid #cbd9ca;background:#f4faef;color:#4c7628;border-radius:6px;padding:7px 10px;cursor:pointer}.actions .reject{background:#fff5f0;border-color:#e6b89d;color:#9b4d2d}.error{color:#a64d3b}`] })
export class ApprovalsComponent implements OnInit {
  private readonly service = inject(ApprovalService);
  private readonly auth = inject(AuthService);
  private readonly api = inject(ApiService);
  readonly requests = signal<ApprovalRequest[]>([]); readonly stores = signal<Store[]>([]); readonly loading = signal(false); readonly error = signal<string|null>(null); readonly submitting = signal(false);
  entityType = ''; entityId = ''; approvalType = ''; storeId = '';
  isManager(): boolean { return this.auth.userContext()?.staffCategory === StaffCategory.StoreManager; }
  ngOnInit(): void { this.load(); if (this.isEmployee()) this.api.get<Store[]>('/stores').subscribe(response => { this.stores.set(response.data ?? []); this.storeId = this.auth.getStoreId() ?? this.stores()[0]?.id ?? ''; }); }
  isEmployee(): boolean { return this.auth.userContext()?.staffCategory === StaffCategory.StoreEmployee; }
  load(): void { this.loading.set(true); const request = this.isManager() ? this.service.pending() : this.service.mine(); request.subscribe({ next: response => { this.requests.set(response.data ?? []); this.loading.set(false); }, error: error => { this.error.set(error.message ?? 'Unable to load approval requests.'); this.loading.set(false); } }); }
  decide(request: ApprovalRequest, approve: boolean): void { const reason = approve ? '' : window.prompt('Rejection reason')?.trim() ?? ''; if (!approve && !reason) return; const operation = approve ? this.service.approve(request.id) : this.service.reject(request.id, reason); operation.subscribe({ next: () => this.load(), error: error => this.error.set(error.message ?? 'Unable to update approval request.') }); }
  submit(): void { if (!this.entityType.trim() || !this.entityId.trim() || !this.approvalType.trim() || !this.storeId) { this.error.set('Complete all request fields.'); return; } this.submitting.set(true); this.service.create({ entityType: this.entityType.trim(), entityId: this.entityId.trim(), approvalType: this.approvalType.trim(), storeId: this.storeId }).subscribe({ next: () => { this.entityType = ''; this.entityId = ''; this.approvalType = ''; this.submitting.set(false); this.load(); }, error: error => { this.error.set(error.message ?? 'Unable to create approval request.'); this.submitting.set(false); } }); }
}