/// Marathi translations. Keys are the English UI strings (see `AppStrings`).
/// Missing keys fall back to English, so partial coverage is safe.
const marathi = <String, String>{
  // Welcome / auth
  'Your trusted neighbourhood shop, now digital': 'तुमचं विश्वासू शेजारचं दुकान, आता डिजिटल',
  'Your local shop,\nnow in your hand.': 'आपलं दुकान,\nआता आपल्या हातात.',
  '{n} min delivery': '{n} मिनिटांत डिलिव्हरी',
  'Fresh & reliable': 'ताजं आणि विश्वासार्ह',
  '10-digit number': '१० अंकी नंबर',
  'Get OTP': 'OTP मिळवा',
  'or continue with': 'किंवा यासह सुरू ठेवा',
  'Log in with email': 'ईमेलने लॉग इन करा',
  'Create account': 'खाते तयार करा',
  'Browse as guest': 'पाहुणा म्हणून पहा',
  'Welcome back': 'पुन्हा स्वागत आहे',
  'Log in to see your orders and saved addresses.': 'तुमच्या ऑर्डर आणि जतन केलेले पत्ते पाहण्यासाठी लॉग इन करा.',
  'Email or phone': 'ईमेल किंवा फोन',
  'Email': 'ईमेल',
  'Password': 'पासवर्ड',
  'Show password': 'पासवर्ड दाखवा',
  'Hide password': 'पासवर्ड लपवा',
  'Forgot password?': 'पासवर्ड विसरलात?',
  'Log in': 'लॉग इन',
  'or': 'किंवा',
  'New here?': 'नवीन आहात?',
  'Create your account': 'तुमचं खाते तयार करा',
  'Sign up in a few seconds and start shopping.': 'काही सेकंदात साइन अप करा आणि खरेदी सुरू करा.',
  'or sign up with email': 'किंवा ईमेलने साइन अप करा',
  'Full name': 'पूर्ण नाव',
  'Mobile number': 'मोबाइल नंबर',
  'I agree to the Terms of Service and Privacy Policy': 'मी सेवा अटी आणि गोपनीयता धोरणाशी सहमत आहे',
  'Already registered?': 'आधीच नोंदणी केली आहे?',
  'Reset password': 'पासवर्ड रीसेट करा',
  'Enter your email and we will send you a reset link.': 'तुमचा ईमेल टाका, आम्ही रीसेट लिंक पाठवू.',
  'Send reset link': 'रीसेट लिंक पाठवा',
  'Check your inbox for a reset link.': 'रीसेट लिंकसाठी तुमचा इनबॉक्स तपासा.',
  'Back to log in': 'लॉग इनवर परत जा',
  'Required': 'आवश्यक',
  'Enter a valid email': 'वैध ईमेल टाका',
  'At least 8 characters': 'किमान ८ अक्षरे',
  'Enter a 10-digit number': '१० अंकी नंबर टाका',
  '{provider} is a design preview; signing in as a demo user.': '{provider} हे डिझाइन प्रिव्ह्यू आहे; डेमो वापरकर्ता म्हणून साइन इन करत आहे.',
  'Verify your number': 'तुमचा नंबर सत्यापित करा',
  'Enter the 6-digit code sent to {phone}': '{phone} वर पाठवलेला ६ अंकी कोड टाका',
  'Resend code in 0:{s}': 'कोड पुन्हा पाठवा 0:{s}',
  'Resend code': 'कोड पुन्हा पाठवा',
  'Verify and continue': 'सत्यापित करा आणि पुढे जा',
  'Change number': 'नंबर बदला',
  'Design preview: any 6 digits will work.': 'डिझाइन प्रिव्ह्यू: कोणतेही ६ अंक चालतील.',

  // Home
  'Good morning': 'शुभ प्रभात',
  'Good afternoon': 'शुभ दुपार',
  'Good evening': 'शुभ संध्याकाळ',
  'friend': 'मित्रा',
  'DELIVER TO': 'येथे पोहोच',
  'Notifications': 'सूचना',
  'No new notifications': 'नवीन सूचना नाहीत',
  'Search tomato, milk, atta…': 'टोमॅटो, दूध, आटा शोधा…',
  'Clear search': 'शोध पुसा',
  'Voice search': 'व्हॉइस शोध',
  'Voice search is coming soon': 'व्हॉइस शोध लवकरच येत आहे',
  'From {store}': '{store} कडून',
  '{km} km away': '{km} किमी अंतरावर',
  'min': 'मिनिटे',
  'to your door': 'तुमच्या दारापर्यंत',
  'Today’s deals': 'आजच्या ऑफर्स',
  'Up to {n}% off': '{n}% पर्यंत सूट',
  'Buy again': 'पुन्हा खरेदी करा',
  'Your past orders': 'तुमच्या मागील ऑर्डर',
  'Shop by category': 'विभागानुसार खरेदी',
  'See all': 'सर्व पहा',
  'Popular near you': 'तुमच्या जवळ लोकप्रिय',
  '{n} results': '{n} निकाल',
  'Clear': 'पुसा',
  'Nothing found': 'काही सापडले नाही',
  'Try a different search.': 'वेगळा शोध वापरून पहा.',

  // Categories
  'Categories': 'विभाग',
  'Everything your local shop has': 'तुमच्या दुकानातलं सगळं काही',
  'Veggies': 'भाज्या',
  'Fruits': 'फळे',
  'Dairy': 'दुग्धजन्य',
  'Grocery': 'किराणा',
  'Snacks': 'स्नॅक्स',
  'Nothing here yet': 'इथे अजून काही नाही',
  'Check back soon.': 'लवकरच पुन्हा पहा.',
  '{n} items': '{n} वस्तू',
  '{n} item': '{n} वस्तू',

  // Product
  'Back': 'मागे',
  'Favourite': 'आवडते',
  'In stock': 'उपलब्ध',
  'Out of stock': 'स्टॉक संपला',
  'Fresh today': 'आज ताजे',
  'Sold by {store}': '{store} कडून विक्री',
  'You save ₹{n}': 'तुमची बचत ₹{n}',
  'You might also like': 'हे देखील आवडेल',
  'Add': 'जोडा',
  'Add one': 'एक जोडा',
  'Remove one': 'एक काढा',
  'Increase quantity': 'संख्या वाढवा',
  'Decrease quantity': 'संख्या कमी करा',
  'Added to cart': 'कार्टमध्ये जोडले',

  // Cart / checkout
  'Cart': 'कार्ट',
  'Your cart': 'तुमचं कार्ट',
  'Your cart is empty': 'तुमचं कार्ट रिकामं आहे',
  'Your cart is empty.': 'तुमचं कार्ट रिकामं आहे.',
  'Add fresh groceries to get started.': 'सुरुवात करण्यासाठी ताजा किराणा जोडा.',
  'Start shopping': 'खरेदी सुरू करा',
  'Add {amt} more for free delivery': 'मोफत डिलिव्हरीसाठी आणखी {amt} जोडा',
  'You unlocked free delivery!': 'तुम्हाला मोफत डिलिव्हरी मिळाली!',
  'Item total': 'वस्तूंची एकूण किंमत',
  'Delivery fee': 'डिलिव्हरी शुल्क',
  'Handling fee': 'हाताळणी शुल्क',
  'FREE': 'मोफत',
  'To pay': 'देय रक्कम',
  'You are saving {amt} on this order': 'या ऑर्डरवर तुम्ही {amt} वाचवत आहात',
  'Checkout': 'चेकआउट',
  'Nothing to check out': 'चेकआउटसाठी काही नाही',
  'Back to shop': 'दुकानात परत जा',
  'Delivering to {label}': '{label} येथे पोहोच',
  'Change': 'बदला',
  'Arriving in about {n} minutes': 'सुमारे {n} मिनिटांत पोहोचेल',
  'Payment method': 'पेमेंट पद्धत',
  'Cash on delivery': 'डिलिव्हरीवर रोख',
  'UPI': 'UPI',
  'Card': 'कार्ड',
  'Order summary': 'ऑर्डर सारांश',
  'Payment is a placeholder in this build; no charge is made.': 'या आवृत्तीत पेमेंट हे केवळ नमुना आहे; कोणतेही शुल्क आकारले जात नाही.',
  'Place order': 'ऑर्डर द्या',

  // Orders
  'Order placed!': 'ऑर्डर दिली!',
  'Order #{id} is being prepared.\nExpected in about {n} minutes.': 'ऑर्डर #{id} तयार होत आहे.\nसुमारे {n} मिनिटांत पोहोचेल.',
  'Track order': 'ऑर्डर ट्रॅक करा',
  'Continue shopping': 'खरेदी सुरू ठेवा',
  'Orders': 'ऑर्डर',
  'Your orders': 'तुमच्या ऑर्डर',
  'No orders yet': 'अजून ऑर्डर नाहीत',
  'Your orders will show up here.': 'तुमच्या ऑर्डर इथे दिसतील.',
  'Order': 'ऑर्डर',
  'Order not found': 'ऑर्डर सापडली नाही',
  'We could not find this order.': 'ही ऑर्डर सापडली नाही.',
  'View orders': 'ऑर्डर पहा',
  'Order placed': 'ऑर्डर दिली',
  'Packed': 'पॅक केले',
  'Out for delivery': 'डिलिव्हरीसाठी निघाले',
  'Delivered': 'पोहोचले',
  'Paid via': 'पेमेंट पद्धत',
  'Total': 'एकूण',
  'Reorder': 'पुन्हा ऑर्डर करा',
  '{n} items · ₹{amt}': '{n} वस्तू · ₹{amt}',

  // Profile
  'Home': 'होम',
  'Profile': 'प्रोफाइल',
  'Guest shopper': 'पाहुणा ग्राहक',
  'Sign in to sync orders and addresses': 'ऑर्डर आणि पत्ते सिंक करण्यासाठी साइन इन करा',
  'Signed in': 'साइन इन केले',
  'My orders': 'माझ्या ऑर्डर',
  '{n} placed': '{n} दिल्या',
  'Saved addresses': 'जतन केलेले पत्ते',
  'Payment methods': 'पेमेंट पद्धती',
  'Help & support': 'मदत आणि सहाय्य',
  'Support': 'सहाय्य',
  '{what} is coming soon': '{what} लवकरच येत आहे',
  'Language': 'भाषा',
  'Appearance': 'दिसणं',
  'System': 'सिस्टम',
  'Light': 'लाइट',
  'Dark': 'डार्क',
  'Sign in / Register': 'साइन इन / नोंदणी',
  'Log out': 'लॉग आउट',

  // Address
  'Delivery address': 'डिलिव्हरी पत्ता',
  'Search area, street or landmark': 'परिसर, रस्ता किंवा खूण शोधा',
  'Use current location': 'सध्याचे स्थान वापरा',
  'Move the map to fine-tune the pin': 'पिन अचूक करण्यासाठी नकाशा हलवा',
  'Flat / house no. / building': 'फ्लॅट / घर क्र. / इमारत',
  'Landmark (optional)': 'जवळची खूण (ऐच्छिक)',
  'Work': 'कामाचे ठिकाण',
  'Other': 'इतर',
  'Confirm location': 'स्थान निश्चित करा',

  // API errors (see lib/data/api/api_exception.dart)
  'Cannot reach the server. Check your connection and try again.': 'सर्व्हरशी संपर्क होत नाही. कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
  'The server took too long to respond. Please try again.': 'सर्व्हरने प्रतिसाद द्यायला खूप वेळ घेतला. कृपया पुन्हा प्रयत्न करा.',
  'Please check the details you entered.': 'कृपया तुम्ही टाकलेली माहिती तपासा.',
  'Please sign in to continue.': 'पुढे जाण्यासाठी कृपया साइन इन करा.',
  'You do not have access to this.': 'तुम्हाला याचा प्रवेश नाही.',
  'We could not find what you were looking for.': 'तुम्ही शोधत असलेले आम्हाला सापडले नाही.',
  'This changed while you were shopping. Please review and try again.': 'तुम्ही खरेदी करत असताना यात बदल झाला. कृपया तपासा आणि पुन्हा प्रयत्न करा.',
  'Too many attempts. Please wait a moment and try again.': 'खूप प्रयत्न झाले. कृपया थोडं थांबून पुन्हा प्रयत्न करा.',
  'Something went wrong on our side. Please try again.': 'आमच्या बाजूने काहीतरी चुकलं. कृपया पुन्हा प्रयत्न करा.',
  'Something went wrong. Please try again.': 'काहीतरी चुकलं. कृपया पुन्हा प्रयत्न करा.',

  // Catalog loading (task 1.7)
  'Retry': 'पुन्हा प्रयत्न करा',
  'Could not load': 'लोड करता आले नाही',
  'Load more': 'आणखी दाखवा',
  'Loading…': 'लोड होत आहे…',
  'All items': 'सर्व वस्तू',
  'Browse the full catalogue': 'संपूर्ण यादी पहा',
  'Groceries': 'किराणा',

  // Store, stock and delivery estimate (tasks 1.2, 1.6, 1.10)
  'We do not deliver here yet': 'आम्ही अजून इथे डिलिव्हरी करत नाही',
  'Only a few left': 'थोडेच शिल्लक',
  'Arriving soon': 'लवकरच पोहोचेल',
  'Order #{id} is being prepared.': 'ऑर्डर #{id} तयार होत आहे.',
  // Accounts (P2)
  'Please wait…': 'कृपया थांबा…',
  'Save': 'जतन करा',
  'An account with this email already exists.': 'या ईमेलने आधीच खाते आहे.',
  'Wrong email or password.': 'ईमेल किंवा पासवर्ड चुकीचा आहे.',
  'This account cannot be used in the customer app.': 'हे खाते ग्राहक अॅपमध्ये वापरता येत नाही.',
  'That code is not valid or has expired. Check it or ask for a new one.': 'हा कोड चुकीचा आहे किंवा संपला आहे. तपासा किंवा नवीन कोड मागवा.',
  'Your current password is not correct.': 'तुमचा सध्याचा पासवर्ड चुकीचा आहे.',
  'Mobile number (optional)': 'मोबाइल नंबर (ऐच्छिक)',
  'Enter your email and we will send you a reset code.': 'तुमचा ईमेल टाका, आम्ही रीसेट कोड पाठवू.',
  'Send reset code': 'रीसेट कोड पाठवा',
  'Enter your code': 'तुमचा कोड टाका',
  'We sent an 8-character code to {email}. It works for 30 minutes.': 'आम्ही {email} वर ८ अक्षरी कोड पाठवला आहे. तो ३० मिनिटे चालेल.',
  'Reset code': 'रीसेट कोड',
  'Enter the 8-character code': '८ अक्षरी कोड टाका',
  'New password': 'नवीन पासवर्ड',
  'Change password': 'पासवर्ड बदला',
  'Send a new code': 'नवीन कोड पाठवा',
  'Password changed. Log in with your new password.': 'पासवर्ड बदलला. नवीन पासवर्डने लॉग इन करा.',
  'Edit profile': 'प्रोफाइल बदला',
  'Your email cannot be changed here.': 'तुमचा ईमेल इथे बदलता येत नाही.',
  'Profile saved': 'प्रोफाइल जतन केले',
  'Password changed. Your other devices were signed out.': 'पासवर्ड बदलला. तुमची इतर उपकरणे लॉग आउट झाली.',
  'Other devices will be signed out.': 'इतर उपकरणे लॉग आउट होतील.',
  'Current password': 'सध्याचा पासवर्ड',
  'Sign in to see your orders': 'ऑर्डर पाहण्यासाठी लॉग इन करा',
  'Your orders are saved to your account.': 'तुमच्या ऑर्डर तुमच्या खात्यात जतन होतात.',
  // Store selection
  'Choose a store': 'दुकान निवडा',
  'Change store': 'दुकान बदला',
  'Nearest': 'सर्वात जवळचे',
  '{n} min': '{n} मिनिटे',
  'Stores that deliver to your address. Pick one to see what it has in stock.': 'तुमच्या पत्त्यावर डिलिव्हरी करणारी दुकाने. त्यांच्याकडे काय उपलब्ध आहे ते पाहण्यासाठी एक निवडा.',
  'No store delivers to this address. Try another address.': 'या पत्त्यावर कोणतेही दुकान डिलिव्हरी करत नाही. दुसरा पत्ता वापरून पहा.',
  'Switch to {store}?': '{store} वर जायचे?',
  'Your cart has items from {store}. Switching store will empty your cart.': 'तुमच्या कार्टमध्ये {store} मधील वस्तू आहेत. दुकान बदलल्यास कार्ट रिकामे होईल.',
  'your current store': 'तुमचे सध्याचे दुकान',
  'Keep shopping': 'खरेदी सुरू ठेवा',
  'Switch store': 'दुकान बदला',
  'Stores near you': 'तुमच्या जवळची दुकाने',
  // Store visibility redesign
  'Close': 'बंद करा',
  'SHOPPING FROM': 'येथून खरेदी',
  'arrives in {n} min': '{n} मिनिटांत पोहोचेल',
  'Stores that deliver to you': 'तुमच्याकडे डिलिव्हरी करणारी दुकाने',
  'See all {n}': 'सर्व {n} पहा',
  'Search in {store}': '{store} मध्ये शोधा',
  'Choose your store': 'तुमचे दुकान निवडा',
  '{n} stores deliver to {address}': '{n} दुकाने {address} वर डिलिव्हरी करतात',
  '{n} stores deliver to {address}. Pick one to see what it has in stock.': '{n} दुकाने {address} वर डिलिव्हरी करतात. त्यांच्याकडे काय उपलब्ध आहे ते पाहण्यासाठी एक निवडा.',
  'You have {n} items from {store}. Switching store will empty your cart.': 'तुमच्या कार्टमध्ये {store} मधील {n} वस्तू आहेत. दुकान बदलल्यास कार्ट रिकामे होईल.',
  'Switch to {store} and empty cart': '{store} वर जा आणि कार्ट रिकामे करा',
  'Switch to {store}': '{store} वर जा',
  'Keep shopping at {store}': '{store} मध्ये खरेदी सुरू ठेवा',
  'See addresses and delivery range': 'पत्ते आणि डिलिव्हरी क्षेत्र पहा',
  'Current store': 'सध्याचे दुकान',
  'Selected': 'निवडलेले',
  'Fastest': 'सर्वात जलद',
  'A to Z': 'अ ते ज्ञ',
  'Shop from {store}': '{store} मधून खरेदी करा',
  '{km} km': '{km} किमी',
  '{km} km away · delivers within {r} km': '{km} किमी दूर · {r} किमीपर्यंत डिलिव्हरी',
  'Check other stores': 'इतर दुकाने पहा',
  // Addresses and delivery location (P4)
  'Edit address': 'पत्ता बदला',
  'Add address': 'पत्ता जोडा',
  'Delivery location': 'डिलिव्हरीचे ठिकाण',
  'Address': 'पत्ता',
  'Find this address': 'हा पत्ता शोधा',
  'Use my current location': 'माझे सध्याचे ठिकाण वापरा',
  'Enter coordinates yourself': 'निर्देशांक स्वतः टाका',
  'Latitude': 'अक्षांश',
  'Longitude': 'रेखांश',
  'Use these coordinates': 'हे निर्देशांक वापरा',
  'Receiver name': 'स्वीकारणाऱ्याचे नाव',
  'Receiver phone': 'स्वीकारणाऱ्याचा फोन',
  'Enter a phone number with 10 to 15 digits.': '१० ते १५ अंकी फोन नंबर टाका.',
  'Save as': 'असे जतन करा',
  'Name this address': 'या पत्त्याला नाव द्या',
  'Looking…': 'शोधत आहे…',
  'Location set': 'ठिकाण निश्चित केले',
  'We deliver here': 'आम्ही इथे डिलिव्हरी करतो',
  'You can still save it, but orders to this address are not possible until a store delivers here.': 'तुम्ही तो जतन करू शकता, पण एखादे दुकान इथे डिलिव्हरी करेपर्यंत या पत्त्यावर ऑर्डर देता येणार नाही.',
  'Type the address first.': 'आधी पत्ता टाका.',
  'We could not find this address. Check it, or use your current location.': 'हा पत्ता सापडला नाही. तो तपासा, किंवा तुमचे सध्याचे ठिकाण वापरा.',
  'Address lookup is not available right now. Use your current location, or enter coordinates below.': 'पत्ता शोध सध्या उपलब्ध नाही. तुमचे सध्याचे ठिकाण वापरा, किंवा खाली निर्देशांक टाका.',
  'Enter valid coordinates, for example 19.0760 and 72.8777.': 'योग्य निर्देशांक टाका, उदा. 19.0760 आणि 72.8777.',
  'Set the location first: find the address or use your current location.': 'आधी ठिकाण निश्चित करा: पत्ता शोधा किंवा तुमचे सध्याचे ठिकाण वापरा.',
  'Save address': 'पत्ता जतन करा',
  'Use this location': 'हे ठिकाण वापरा',
  'Delivery addresses': 'डिलिव्हरीचे पत्ते',
  'Delivering to': 'येथे डिलिव्हरी',
  'Current location': 'सध्याचे ठिकाण',
  'Enter an address': 'पत्ता टाका',
  'Save addresses to your account': 'पत्ते तुमच्या खात्यात जतन करा',
  'Sign in to keep your addresses, set a default and use them at checkout.': 'तुमचे पत्ते ठेवण्यासाठी, डिफॉल्ट ठरवण्यासाठी आणि चेकआउटमध्ये वापरण्यासाठी साइन इन करा.',
  'You have no saved addresses yet. Add one so we can find the stores that deliver to you.': 'अजून कोणताही पत्ता जतन केलेला नाही. एक जोडा, म्हणजे तुमच्याकडे डिलिव्हरी करणारी दुकाने आम्हाला शोधता येतील.',
  'Add new address': 'नवीन पत्ता जोडा',
  'Default': 'डिफॉल्ट',
  'More': 'अधिक',
  'Edit': 'बदला',
  'Make default': 'डिफॉल्ट करा',
  'Delete': 'हटवा',
  'Delete this address?': 'हा पत्ता हटवायचा?',
  'Cancel': 'रद्द करा',
  'Change delivery address?': 'डिलिव्हरीचा पत्ता बदलायचा?',
  'Your cart has items from {store}, which does not deliver to this address. Changing the address will empty your cart.': 'तुमच्या कार्टमध्ये {store} मधील वस्तू आहेत, पण ते दुकान या पत्त्यावर डिलिव्हरी करत नाही. पत्ता बदलल्यास कार्ट रिकामे होईल.',
  'Keep current address': 'सध्याचा पत्ता ठेवा',
  'Change and empty cart': 'बदला आणि कार्ट रिकामे करा',
  'We need permission to use your location. You can enter an address instead.': 'तुमचे ठिकाण वापरण्यासाठी परवानगी हवी आहे. तुम्ही त्याऐवजी पत्ता टाकू शकता.',
  'Could not get your location. Try again, or enter an address.': 'तुमचे ठिकाण मिळाले नाही. पुन्हा प्रयत्न करा, किंवा पत्ता टाका.',
  'Location permission needed': 'ठिकाणाची परवानगी हवी',
  'QuickCart cannot see your location because permission was turned off. You can allow it in the app settings, or enter an address instead.': 'परवानगी बंद केल्यामुळे QuickCart ला तुमचे ठिकाण दिसत नाही. तुम्ही ती अॅप सेटिंग्जमध्ये चालू करू शकता, किंवा त्याऐवजी पत्ता टाका.',
  'Location is off': 'ठिकाण बंद आहे',
  'Turn on location on your phone to use your current location, or enter an address instead.': 'सध्याचे ठिकाण वापरण्यासाठी फोनवर लोकेशन चालू करा, किंवा त्याऐवजी पत्ता टाका.',
  'Not now': 'आत्ता नको',
  'Open settings': 'सेटिंग्ज उघडा',
  'You have reached the limit of saved addresses. Delete one to add another.': 'जतन केलेल्या पत्त्यांची मर्यादा गाठली आहे. नवीन जोडण्यासाठी एक हटवा.',
  'This address no longer exists.': 'हा पत्ता आता अस्तित्वात नाही.',
  'Choose location': 'ठिकाण निवडा',
  'Where should we deliver?': 'आम्ही कुठे डिलिव्हरी करावी?',
  'Add your location to see the stores that deliver to you.': 'तुमच्याकडे डिलिव्हरी करणारी दुकाने पाहण्यासाठी तुमचे ठिकाण जोडा.',
  'Try another address': 'दुसरा पत्ता वापरून पहा',
  'Add an address': 'पत्ता जोडा',
  'Choose a delivery address': 'डिलिव्हरीचा पत्ता निवडा',
  'We need an address to deliver to.': 'डिलिव्हरीसाठी आम्हाला पत्ता हवा आहे.',
  'Choose': 'निवडा',
  'We do not deliver to this address yet. Choose another address to place your order.': 'आम्ही अजून या पत्त्यावर डिलिव्हरी करत नाही. ऑर्डर देण्यासाठी दुसरा पत्ता निवडा.',
};
