// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCommerce.Infrastructure.Persistence;

#nullable disable

namespace QuickCommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuickCommerceDbContext))]
    [Migration("20260907115350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCommerce.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "Dairy"
                        });
                });

            modelBuilder.Entity("QuickCommerce.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("StoreId", "CreatedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QuickCommerce.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("QuickCommerce.Domain.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistory");
                });

            modelBuilder.Entity("QuickCommerce.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("CategoryId", "IsActive");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Fresh red tomatoes",
                            ImageUrl = "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=640",
                            IsActive = true,
                            Name = "Tomato",
                            Price = 45m,
                            Sku = "VEG-TOM",
                            UnitOfMeasure = "1 kg"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Everyday cooking potatoes",
                            ImageUrl = "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=640",
                            IsActive = true,
                            Name = "Potato",
                            Price = 38m,
                            Sku = "VEG-POT",
                            UnitOfMeasure = "1 kg"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Pasteurized full cream milk",
                            ImageUrl = "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=640",
                            IsActive = true,
                            Name = "Farm Milk",
                            Price = 34m,
                            Sku = "DAI-MILK",
                            UnitOfMeasure = "500 ml"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Crisp and naturally sweet",
                            ImageUrl = "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=640",
                            IsActive = true,
                            Name = "Royal Gala Apples",
                            Price = 149m,
                            Sku = "FRT-APL",
                            UnitOfMeasure = "1 kg"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Long grain rice for every meal",
                            ImageUrl = "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=640",
                            IsActive = true,
                            Name = "Daily Rice",
                            Price = 89m,
                            Sku = "GRO-RICE",
                            UnitOfMeasure = "1 kg"
                        });
                });

            modelBuilder.Entity("QuickCommerce.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("float(9)");

                    b.Property<double>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("float(9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<double>("ServiceRadiusKm")
                        .HasPrecision(9, 2)
                        .HasColumnType("float(9)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Address = "12 Marine Drive",
                            IsActive = true,
                            Latitude = 19.076000000000001,
                            Longitude = 72.877700000000004,
                            Name = "Harbor Point Dark Store",
                            ServiceRadiusKm = 8.0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Address = "44 Cedar Avenue",
                            IsActive = true,
                            Latitude = 19.102,
                            Longitude = 72.915999999999997,
                            Name = "Cedar Market Hub",
                            ServiceRadiusKm = 7.0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Address = "8 Station Road",
                            IsActive = true,
                            Latitude = 19.045000000000002,
                            Longitude = 72.899000000000001,
                            Name = "North Star Fulfillment",
                            ServiceRadiusKm = 9.0
                        });
                });

            modelBuilder.Entity("QuickCommerce.Domain.StoreInventory", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ReorderThreshold")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("StoreInventory");

                    b.HasData(
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000001"),
                            AvailableQuantity = 24,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000002"),
                            AvailableQuantity = 8,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000003"),
                            AvailableQuantity = 0,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000004"),
                            AvailableQuantity = 16,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000005"),
                            AvailableQuantity = 5,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000001"),
                            AvailableQuantity = 28,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000002"),
                            AvailableQuantity = 12,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000003"),
                            AvailableQuantity = 4,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000004"),
                            AvailableQuantity = 20,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000005"),
                            AvailableQuantity = 9,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000001"),
                            AvailableQuantity = 32,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000002"),
                            AvailableQuantity = 16,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000003"),
                            AvailableQuantity = 8,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000004"),
                            AvailableQuantity = 24,
                            ReorderThreshold = 5
                        },
                        new
                        {
                            StoreId = new Guid("30000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000005"),
                            AvailableQuantity = 13,
                            ReorderThreshold = 5
                        });
                });

            modelBuilder.Entity("QuickCommerce.Domain.Category", b =>
                {
                    b.HasOne("QuickCommerce.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QuickCommerce.Domain.Order", b =>
                {
                    b.HasOne("QuickCommerce.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickCommerce.Domain.OrderItem", b =>
                {
                    b.HasOne("QuickCommerce.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickCommerce.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickCommerce.Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("QuickCommerce.Domain.Order", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickCommerce.Domain.Product", b =>
                {
                    b.HasOne("QuickCommerce.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickCommerce.Domain.StoreInventory", b =>
                {
                    b.HasOne("QuickCommerce.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCommerce.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickCommerce.Domain.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
